### PR TITLE
test that timestamp is unsigned int

### PR DESCRIPTION
**Pull request by staltz**
See https://github.com/ssb-ngi-pointer/bendy-butt-spec/issues/20

### CODE REVIEW

**Comment by arj03** [comment]
Good to know this already works :)

While we are at it, it would be nice to fix [this](https://github.com/ssb-ngi-pointer/ssb-bendy-butt/blob/52d700e9c3ee78a4aebe3fd12802f9c90b9e1089/index.js#L188) one as well.

**Review by mycognosist — APPROVED** [review]
🟢

**Comment by staltz** [comment]
Updated! How does the validation code look like?

**Review by arj03 — APPROVED** [review]
Perfect, thanks :)

**Pull request merged**
