### PR TITLE
box2 fixes

### PR DESCRIPTION
**Pull request by arj03**
I upgraded ssb-db2-box2 to all the latest dependencies and found a few problems. This PR fixes 2 problems related to box2 encoding.

### CODE REVIEW

**Comment by arj03** [comment]
Related test failures: https://github.com/ssb-ngi-pointer/ssb-db2-box2/runs/3505227322

**Review by staltz — APPROVED** [review]
Just looking at code on mobile, it looks very correct

**Comment by arj03** [comment]
Thanks :)

**Comment by arj03** [comment]
Now 🍏 https://github.com/ssb-ngi-pointer/ssb-db2-box2/runs/3505867681

**Pull request merged**
